### ISSUE TITLE
Truffle migration

### ISSUE THREAD

**Issue by lemonmill** [Ty-Sir/avax-nft-monkeys#1]
Hi, how to deploy contracts via Truffle? What arguments needs?

**Comment by Ty-Sir** [comment]
@lemonmill Truffle was giving issues so I ended up deploying via Remix, the constructor parameters for Monkeys.sol are: 
mintPrice: 444000000000000000
_uriBase: <your base URI>
_uriExt: ".json" (only if needed)

And Marketplace.sol does not require any.
