### ISSUE TITLE
error when building

### ISSUE THREAD

**Issue by bscdapps** [Ty-Sir/avax-nft-monkeys#2]
when I try and build a Development server, I get the following error. 

" Error
could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.5.2) " 

not sure what the issue is because when I visit your link it connects fine

**Comment by Ty-Sir** [comment]
@bscdapps It is most likely because I have it hosted using netlify which I am using to take care of three environment variables. Two of which are in `src/App.jsx`, the appId and serverUrl, and another in `src/hooks/useSpeedyProvider.jsx`, my custom node URL. For testing locally you can just use them directly and you should have no problem with the build

**Comment by devburaq** [comment]
@Ty-Sir I also get gas error when I want to mint. Why might it be caused?

**Comment by Ty-Sir** [comment]
@7777nft Are you getting the error when you visit avaxmonkeys.xyz or when you're running a local copy?

**Comment by devburaq** [comment]
@Ty-Sir  I created my own smart contract. I get it when I try to mint on a remix.

**Comment by Ty-Sir** [comment]
@7777nft Oh that is because the contract is pausable and if you look in the constructor, on deployment it calls pause(true), which pauses the contract. So just call pause(false) and then you should be able to mint no problem. And then obviously make sure you are sending the correct value that corresponds to the mintPrice you set for the amount you are minting

**Comment by devburaq** [comment]
@Ty-Sir Yes I know that and I did false. Yet I keep getting the same error. I thought the contract owner didn't have mint authority. :)

**Comment by Ty-Sir** [comment]
@7777nft Ah ok, yes the owner can mint in this contract, they have to pay the same as anyone else.  I just copy and pasted the contract into Remix and minted no problem. Are you setting the correct send value for the amount you are minting?

<img width="324" alt="remix screenshot" src="https://user-images.githubusercontent.com/67834313/159732019-7e900c34-125c-4773-87c8-9c519b505c95.png">

**Comment by devburaq** [comment]
@Ty-Sir Yes it looks correct. Actually I've published many contracts before and I didn't have this problem. I've been searching the internet but haven't found a solution yet. I will continue researching.

**Comment by Ty-Sir** [comment]
@7777nft Sometimes Remix can get confused, try deleting the `artifacts` folder and then clicking on the contract again so it can compile again. Also, make sure all the files in the `.deps` folder have artifacts as well. Sometimes Remix doesn't install all the OpenZeppelin contracts correctly.

**Comment by devburaq** [comment]
@Ty-Sir Thanks for your interest, I will try.

**Comment by bscdapps** [comment]
<img width="495" alt="Screen Shot 2022-03-25 at 1 56 19 pm" src="https://user-images.githubusercontent.com/75070913/160046582-9e324770-d659-42ac-974f-4365630913fe.png">

I get this error before I can connect metamask when I build locally or build and host on netlify with no changes to the code

**Comment by devburaq** [comment]
@Ty-Sir Do we need to additionally make a moralis connection? If yes, I couldn't see the settings for app and serverurl.

**Comment by Ty-Sir** [comment]
@bscdapps Do you have a moralis account and add the correct node URL for avax mainet in place of the env var in `src/hooks/useSpeedyProvider.jsx`?

**Comment by Ty-Sir** [comment]
@7777nft Yes to run the dapp you need a Moralis account, it is free. I'll make the README with detailed instructions on how to get it running today and you'll have no problem getting it running

**Comment by Ty-Sir** [comment]
@7777nft @bscdapps I made a video tutorial that covers everything to get the dapp running, check the README ✌️
